extern void delay_sec(unsigned int sec);
extern void delay_ms(unsigned int ms);
extern void lcd_data(unsigned char data);
extern void lcd_cmd(unsigned char cmd);
extern void lcd_init(void);
extern void lcd_string(char *p);
extern void lcd_integer(int num);
extern void lcd_float(float num);
extern void lcd_cgram(void );
extern void uart0_init(unsigned int baud);
extern void uart0_tx(unsigned char data);
extern unsigned char uart0_rx(void);
extern void uart0_tx_string(char *ptr);
extern void uart0_hex(unsigned char temp);
extern void uart0_binary(unsigned int temp);
extern void i2c_init(void);
extern void i2c_byte_write_frame(unsigned char sa,unsigned char mr,unsigned char data);
extern unsigned char i2c_byte_read_frame(unsigned char sa,unsigned char mr);
extern void config_vic_for_eint0(void);
extern void config_eint0(void);
extern void config_vic_for_uart0(void);
extern void config_uart0(void);

typedef unsigned int u32;
